[package]
name = "rayan-cloud"
version = "0.1.0"
edition = "2021"

[dependencies]
rayan-core = { path = "../core" }
axum = "0.7.5"
tokio = { workspace = true, features = ["full"] }
sqlx = { version = "0.7", default-features = false, features = ["sqlite", "runtime-tokio-rustls", "macros"] }
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
tracing.workspace = true
tracing-subscriber = "0.3"
anyhow.workspace = true
