name: Security Audit

on:
  schedule:
    - cron: '0 0 * * *' # Run daily
  push:
    paths:
      - '**/Cargo.lock'

jobs:
  security_audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install cargo-audit
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: cargo-audit
          
      - name: Run cargo-audit
        run: cargo audit
